disabled_rules: #rule identifiers to exclude from running
- line_length
- function_body_length
- type_body_length

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- FitCat-UI/
- FitCat2/Animations



